version: "2.4"

services:
  transcript_ui_front:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    hostname: transcript_ui_front
    container_name: transcript_ui_front
    ports:
      - '9000:8000'
    env_file:
      - .env
    volumes:
      - .:/opt/alloxentric
      - node_modules:/opt/alloxentric/node_modules
    environment:
      - PORT=8000
      - npm_config_unsafe_perm=true
      - NODE_ENV=development

volumes:
  node_modules: null

networks:
  default:
    name: alloxentric.com
